name: complete_shop_clone
description: A new Flutter project

publish_to: 'none'

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  # State Management
  provider: ^6.1.2
  flutter_bloc: ^8.1.4

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.2.5
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo.jpeg
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
