// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRODA0laetsWBt4l-mLWFjPFeKt7gP6lo',
    appId: '1:606043371704:web:4b57bdf48893183e829c4d',
    messagingSenderId: '606043371704',
    projectId: 'e-commerce-app-d5951',
    authDomain: 'e-commerce-app-d5951.firebaseapp.com',
    databaseURL: 'https://e-commerce-app-d5951-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'e-commerce-app-d5951.firebasestorage.app',
    measurementId: 'G-6VCC86RJW6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwOdg6WlRjt93nWTLFzDG-f3wdZspzNPM',
    appId: '1:606043371704:android:1d06d6b82582ca0e829c4d',
    messagingSenderId: '606043371704',
    projectId: 'e-commerce-app-d5951',
    databaseURL: 'https://e-commerce-app-d5951-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'e-commerce-app-d5951.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAISeqIahbxSIZRMKEDpVLvu7lQWeLSzjQ',
    appId: '1:606043371704:ios:719734e0f03afe1e829c4d',
    messagingSenderId: '606043371704',
    projectId: 'e-commerce-app-d5951',
    databaseURL: 'https://e-commerce-app-d5951-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'e-commerce-app-d5951.firebasestorage.app',
    iosClientId: '606043371704-gffktu4ge7ovfvfsnfng29jthlon88k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.completeShopClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAISeqIahbxSIZRMKEDpVLvu7lQWeLSzjQ',
    appId: '1:606043371704:ios:719734e0f03afe1e829c4d',
    messagingSenderId: '606043371704',
    projectId: 'e-commerce-app-d5951',
    databaseURL: 'https://e-commerce-app-d5951-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'e-commerce-app-d5951.firebasestorage.app',
    iosClientId: '606043371704-gffktu4ge7ovfvfsnfng29jthlon88k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.completeShopClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRODA0laetsWBt4l-mLWFjPFeKt7gP6lo',
    appId: '1:606043371704:web:0bf928668b8c9334829c4d',
    messagingSenderId: '606043371704',
    projectId: 'e-commerce-app-d5951',
    authDomain: 'e-commerce-app-d5951.firebaseapp.com',
    databaseURL: 'https://e-commerce-app-d5951-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'e-commerce-app-d5951.firebasestorage.app',
    measurementId: 'G-D7JCLPEPER',
  );

}